appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: atKT//LKNOegD4/ThDzZVbSGlutd+cPaKgkdkmA82G1az2sSyDMd9i5sbZnAmuYCAW+BwpcDlx2EtenbrdLZKR83nKzmbbnOJ7+1qccLNRlRiYfQFQLodxjVB1iLHgQi6fZ+ORIPfAcL80fY8b10/KzDXUSHi70LX6h6ISINEgav9xJVsS/hyvoPemnpXZhjIiouNPbNDjXknT4GTKvhuY0gV8c8uFs7zq+9o3I2yxr4V9kpkMcC502Q9OvkvhZfMp9d7UAothdJ6IalvsJnybJV+w+FunZlDqeuLupUNg7oM/9GJ3g0v8uehvhfvDVn55DSx+KCm3uBQ6X8Rf2k6Dcx6HWA01/RTT3GQK9LGxLremWYhCSdrIDniaQhTBwsN6T+jC8YOuVXf/E86w7i1yJuiVFw1KD9J8v8QYfb68/UtsS7tE7UGHui81ZOeL8SYOulry7omTgGzJ/7+icz4dTgO2AUmEbi/FFIDpZNtYaUfHEtP4JbKAjnmxAq3hssvVp2qMxR4EkPqe92HnWuCMLgs1UvEMDbkdHQU4ExAGQ27YrxnZ4a0h9iQd3IK/lej6SAuRfnorIed661c09UooYZLxwsIImadDPRY79XLGyXK20yxQoWbp49cG5SPS12E/lSYCLzA9uOQOqXeRAkdeZIkW3/UBO62lZXkdcyAbw=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
